#ifndef HOST_DEFINES_H_INCLUDED
#define HOST_DEFINES_H_INCLUDED

/*
 * This file holds all defines necessary for the host.
 *
 * This can be helpful for returning the specific returncodes from
 * your hosts, while preventing linking issues.
 */


#define HOST_VERSION_MAJOR 0
#define HOST_VERSION_MINOR 5
#define HOST_VERSION_MINI 0

#define HOST_UP 0
#define HOST_DOWN 1
#define HOST_LEFT 2
#define HOST_RIGHT 3
#define HOST_ACTION 4
#define HOST_BUTTON1 5
#define HOST_BUTTON2 6
#define HOST_BUTTON3 7
#define HOST_BUTTON4 8
#define HOST_BUTTON5 9
#define HOST_BUTTON6 10

#define HOST_BUTTONCOUNT 11

#define HOST_RETURNCODE_USEFIXEDFUNCTION 0
#define HOST_RETURNCODE_USEINPUTMETHODS 1
#define HOST_RETURNCODE_USECALLBACK 2
#define HOST_RETURNCODE_TRUE 3
#define HOST_RETURNCODE_FALSE 4
#define HOST_RETURNCODE_SUCCESS 5
#define HOST_RETURNCODE_FAIL 6
#define HOST_RETURNCODE_FAIL_INVALID_TYPE 7

//Different types of outputs
#define HOST_OUTPUT_TYPE_INTEGER 0
#define HOST_OUTPUT_TYPE_FLOAT 1
#define HOST_OUTPUT_TYPE_DOUBLE 2
#define HOST_OUTPUT_TYPE_STRING 3
#define HOST_OUTPUT_TYPE_COLOR 4
#define HOST_OUTPUT_TYPE_BOOL 5
#define HOST_OUTPUT_TYPE_RANGED_INTEGER 6
#define HOST_OUTPUT_TYPE_RANGED_FLOAT 7
#define HOST_OUTPUT_TYPE_RANGED_DOUBLE 8

//Different positions of the output possibilities
#define HOST_OUTPUT_POS_FRONT 0
#define HOST_OUTPUT_POS_LEFT 1
#define HOST_OUTPUT_POS_RIGHT 2
#define HOST_OUTPUT_POS_UPPER_FRONT 3
#define HOST_OUTPUT_POS_LOWER_FRONT 4
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_1 5
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_2 6
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_3 7
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_4 8
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_5 9
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_6 10
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_7 11
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_8 12
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_9 13
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_10 14
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_11 15
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_12 16
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_13 17
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_14 18
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_15 19
#define HOST_OUTPUT_POS_CONTROLS_PLAYER_16 20

//Bitwise defined position (for further specification of the ositin of the output)
#define HOST_OUTPUT_POS_1 32
#define HOST_OUTPUT_POS_2 64
#define HOST_OUTPUT_POS_3 128
#define HOST_OUTPUT_POS_4 256
#define HOST_OUTPUT_POS_5 512
#define HOST_OUTPUT_POS_6 1024

//Typedef for the callback function function pointer
typedef void (*host_input_callback_func)(int, int, int);

#endif
