BOARD_TAG 			= nano
BOARD_SUB 			= atmega328
MONITOR_PORT 		= /dev/ttyUSB0
ARDUINO_DIR 		= /usr/share/arduino
AVR_TOOLS_DIR 		= /usr
AVRDUDE_CONF 		= /etc/avrdude.conf
ARDUINO_LIBS 		= 
MONITOR_BAUDRATE 	= 115200

include ../Arduino-Makefile/Arduino.mk 		# The main arduino makefile

